name: bonsoir_android
description: Android implementation of the Bonsoir plugin.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_android
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 5.1.5

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: bonsoir
    platforms:
      android:
        package: fr.skyost.bonsoir
        pluginClass: BonsoirPlugin

dependencies:
  bonsoir_platform_interface: #^5.1.3
    git:
      url: https://github.com/InvisibleWrench/Bonsoir.git
      path: packages/bonsoir_platform_interface

dependency_overrides:
  bonsoir_platform_interface:
    path: ../bonsoir_platform_interface/
