name: bonsoir_platform_interface
description: Common platform interface for the Bonsoir plugin.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_platform_interface
version: 5.1.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ">=1.10.0 <2.0.0"
  plugin_platform_interface: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^4.0.0
